In [13]:
import sys
sys.path.append("../../")
from STK_Sim import *
from Optimizers import *

# Filename = 'AERO_402_Further_Assessment'

# stk_object = STK_Simulation(False,Filename)

In [4]:
# Loading targets into stk from file.
stk_object.set_sim_time(days=0, hours=1)
stk_object.Target_Loader("../../Input_Files/Target_Packages/Targets_15.txt")

In [ ]:
cost_df = pd.read_csv('../../Input_Files/Cost.csv')
historical_df = pd.read_csv('../../Pop_Over_Gen/historical.csv')
opt = MultiObjectiveOptimizer(stk_object,n_pop=100,n_gen=10,historical_df=historical_df,cost_df=cost_df)
print("Beginning Optimization")
# hof = opt.run(read=False,enable_print=False)
# pd.DataFrame([hof[0]], columns = 'Alt,Inc,Init_RAAN,Delta_RAAN,N_sats,N_planes'.split(','))

In [12]:
def prog_cost_function(self, Individual):
    cost_df = self.cost_df  

    cost_per_launch = 1500000

    n_planes = Individual[5]
    n_sats = Individual[4]

    operations_cost = 132565233
    first_sat_cost = cost_df['First_Sat_Cost'].sum()
    additional_sats_cost = (cost_df['Add_Sat_Cost']*(n_sats-1)).sum()
    launch_costs = cost_per_launch*n_planes
    
    total_cost = operations_cost +  first_sat_cost + additional_sats_cost + launch_costs
    return total_cost

prog_cost_function(opt,[0,0,0,0,12,12])

136281931.8328822

In [ ]:
def choose_LV(Individual=[0,0,0,0,12,12]):
    n_planes = Individual[5]
    n_sats = Individual[4]
    mass = 250
    dimensions = 500

In [73]:
LVs = pd.read_csv('../../Input_Files/LVs.csv')
LVs = LVs[LVs['Status'] == 'Operational']
LVs['Sat Capacity'] = (LVs['Performance [kgs]']//240).astype(int)
LVs['Cost per Sat'] = (LVs['Cost [$M]']/LVs['Sat Capacity']).round(1)
LVs = LVs[LVs['Sat Capacity'] > 0]

In [74]:
LVs.sort_values(by='Cost per Sat')

,Organization,Launcher,First Launch,Status,Launches,Cost [$M],Performance [kgs],Sat Capacity,Cost per Sat
38,ISRO,SSLV,2022,Operational,2,4.2,500.0,2,2.1
12,ExPace / CASIC,Kuaizhou-11 (KZ-11),2020,Operational,3,10.0,1000.0,4,2.5
8,ABL,RS1,2023,Operational,1,12.0,1000.0,4,3.0
33,Galactic Energy,Ceres-1,2020,Operational,13,4.5,300.0,1,4.5
3,KARI,Nuri (KSLV-2),2021,Operational,3,30.0,1500.0,6,5.0
28,i-Space,Hyperbola-1 (Shuang Quxian),2019,Operational,6,5.0,300.0,1,5.0
24,ExPace / CASIC,Kuaizhou-1A (Fei Tian 1),2017,Operational,26,6.0,300.0,1,6.0
6,Firefly,Alpha,2021,Operational,4,15.0,630.0,2,7.5
2,Northrop Grumman,Minotaur C (Taurus-XL),1994,Operational,12,50.0,1054.0,4,12.5
1,Northrop Grumman,Pegasus (XL),1990,Operational,45,56.0,443.0,1,56.0

In [66]:
LVs[(LVs['Performance [kgs]']  < 500) & (LVs['Performance [kgs]']  > 400)].sort_values(by='Cost [$M]').iloc[0:6]

,Organization,Launcher,First Launch,Status,Launches,Cost [$M],Performance [kgs],Cost per kg
1,Northrop Grumman,Pegasus (XL),1990,Operational,45,56.0,443.0,126410.8

In [61]:
LVs[(LVs['Performance [kgs]']  < 800) & (LVs['Performance [kgs]']  > 150)].sort_values(by='Cost [$M]').iloc[0]

Organization                ISRO
Launcher                    SSLV
First Launch                2022
Status               Operational
Launches                       2
Cost [$M]                    4.2
Performance [kgs]          500.0
Cost per kg               8400.0
Name: 38, dtype: object

In [62]:
LVs[(LVs['Performance [kgs]']  < 1000) & (LVs['Performance [kgs]']  > 150)].sort_values(by='Cost [$M]').iloc[0]

Organization                ISRO
Launcher                    SSLV
First Launch                2022
Status               Operational
Launches                       2
Cost [$M]                    4.2
Performance [kgs]          500.0
Cost per kg               8400.0
Name: 38, dtype: object

In [39]:


fig = go.Figure()
fig.add_trace(go.Scatter(x=LVs['Cost [$M]'], y=LVs['Performance [kgs]'],mode='markers',hovertext=LVs.apply(lambda row: '<br>'.join([f'{col}: {row[col]}' for col in LVs.columns]), axis=1)))
fig.update_layout(title=f'LVs',xaxis_title=f'{'Cost [$M]'}',yaxis_title=f'{'Performance [kgs]'}')

fig.show()