In [1]:
import sys
sys.path.append("../../")
from Scripts import *

In [21]:
df = pd.read_csv('../../Pop_Over_Gen/historical.csv')
df = df[df['Num_Planes'] <= df['Num_Sats']]

df['Cost'] = df['Cost']/10**6
df[['Avg_Percentage','Avg_Time','Cost']] = df[['Avg_Percentage','Avg_Time','Cost']] .round(2)
# df = df.drop(df.columns[-1], axis=1)
df = df[(df['Avg_Percentage'] == 100)]
df['Num_Planes'] = df['Num_Planes'].astype(int)
df = df.sort_values(by='Num_Planes')
df = df.reset_index(drop=True)
# df = df[df['Num_Planes'] == 11]
# df = df.sort_values(by='Cost')
df

,Alt,Inc,Initial_Raan,Delta_Raan,Num_Sats,Num_Planes,Avg_Percentage,Avg_Time,Cost
0,626.0,91.0,81.0,5.0,12,3,100.0,16.04,172.28
1,628.0,96.0,93.0,21.0,9,3,100.0,17.33,171.48
2,622.0,96.0,31.0,23.0,6,4,100.0,20.70,182.68
3,622.0,95.0,31.0,22.0,7,4,100.0,18.29,182.95
4,600.0,97.0,115.0,18.0,10,4,100.0,15.39,183.75
...,...,...,...,...,...,...,...,...,...
121,596.0,93.0,58.0,27.0,11,11,100.0,12.83,268.02
122,590.0,89.0,150.0,12.0,11,11,100.0,13.40,268.02
123,596.0,90.0,30.0,27.0,11,11,100.0,13.50,268.02
124,587.0,92.0,63.0,28.0,11,11,100.0,13.67,268.02
125,602.0,91.0,123.0,29.0,11,11,100.0,13.04,268.02

In [7]:
pareto = create_pareto(df, objective1='Cost', objective2='Avg_Time',obj1_type=-1, obj2_type=-1)
pareto['Avg_Percentage'] = pareto['Avg_Percentage'].astype(str)+' %'
pareto.to_csv('../../Pop_Over_Gen/pareto.csv',index=False)

In [15]:
# sum - Adds up values across groups. Useful if you want total values.
# min / max - Gets the minimum or maximum values, respectively.
# std - Calculates the standard deviation, which can help understand the variability of data within groups.
# var - Returns the variance, giving another measure of spread within the data.
# median - Calculates the median value, helpful for understanding central tendency, especially for skewed data.
# count - Counts the number of occurrences in each group. This is useful if you want to know how many entries are in each category.
# first / last - Returns the first or last value in the group.
# prod - Calculates the product of all values in the group (might be less common but useful in some cases).

pivot_df = df[df.columns.to_list()[4:]]
pivot_df = pivot_df.reset_index().drop(columns='index')
pivot_df['Num_Designs'] = pivot_df.index

values = ['Num_Designs', 'Avg_Time','Cost']
pivot_table = pivot_df.pivot_table(
    index=['Num_Planes'],         
    # columns=['Num_Sats'],
    values=values,
    aggfunc={'Num_Designs': 'count', 'Avg_Time': 'max', 'Cost': 'mean'}
)
pivot_table.round(2)

            Avg_Time    Cost  Num_Designs
Num_Planes
3              17.33  171.88            2
4              20.70  183.22           15
5              25.68  195.19           26
6              21.94  207.34           20
7              21.27  219.45           19
8              17.50  231.59           15
9              18.25  243.67           14
10             13.77  255.85            8
11             13.88  268.02            7

In [29]:
historical_df = pd.read_csv('../../Pop_Over_Gen/historical.csv')

historical_df['Cost'] = historical_df['Cost']/10**6
historical_df[['Avg_Percentage','Avg_Time','Cost']] = historical_df[['Avg_Percentage','Avg_Time','Cost']] .round(2)
historical_df = historical_df[(historical_df['Avg_Percentage'] == 100)]
historical_df = historical_df.reset_index(drop=True)


for num_planes in range(3,12):
    df = historical_df[historical_df['Num_Planes'] == num_planes]
    df = df.reset_index(drop=True)
    df = df.sort_values(by='Cost')
    Load_Individual(df.iloc[0].to_list())
    pd.read_csv('../../Input_Files/Satellites_File.txt').to_csv(f'../../Input_Files/Constellations/{num_planes}.txt',index=False)

[628.0, 96.0, 93.0, 21.0, 9.0, 3.0, 100.0, 17.33, 171.48]
[622.0, 96.0, 31.0, 23.0, 6.0, 4.0, 100.0, 20.7, 182.68]
[630.0, 92.0, 128.0, 16.0, 5.0, 5.0, 100.0, 24.8, 194.42]
[616.0, 92.0, 136.0, 6.0, 6.0, 6.0, 100.0, 20.87, 206.68]
[594.0, 91.0, 124.0, 30.0, 7.0, 7.0, 100.0, 21.27, 218.95]
[598.0, 91.0, 117.0, 30.0, 8.0, 8.0, 100.0, 16.61, 231.22]
[604.0, 92.0, 67.0, 25.0, 9.0, 9.0, 100.0, 14.55, 243.48]
[589.0, 95.0, 42.0, 13.0, 10.0, 10.0, 100.0, 12.66, 255.75]
[581.0, 93.0, 95.0, 25.0, 11.0, 11.0, 100.0, 13.88, 268.02]

In [28]:
df = historical_df[historical_df['Num_Planes'] == 12]
df = df.reset_index(drop=True)
df = df.sort_values(by='Cost')
df.iloc[0].to_list()

IndexError: single positional indexer is out-of-bounds